WITH INFO AS (
    SELECT CAR.DAILY_FEE, HIS.HISTORY_ID, DATEDIFF(HIS.END_DATE, HIS.START_DATE) +1 AS PERIOD,
    CASE 
        WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) +1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) +1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(HIS.END_DATE, HIS.START_DATE) +1 >= 7 THEN '7일 이상'
        ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR
    ON HIS.CAR_ID = CAR.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)

SELECT INFO.HISTORY_ID, ROUND(INFO.DAILY_FEE * INFO.PERIOD * (100-IFNULL(PLAN.DISCOUNT_RATE, 0))/100) AS FEE
FROM INFO LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON INFO.DURATION_TYPE=PLAN.DURATION_TYPE AND PLAN.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC
